FROM ubuntu:18.10
#RUN apk update
#RUN apk add --no-cache python3 py-pip
#RUN apt-get -y update && apt-get -y upgrade && 
#RUN apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev libaio1 libaio-dev
RUN apt-get install python3

